### PR TITLE
replaced libclang with clang and clang-tools packages from conda-forge

### PR DESCRIPTION
**Pull request by teju85**
This is in addition to the PR https://github.com/rapidsai/gpuci-build-environment/pull/68 as per @mike-wendt 's suggestion on that PR.

### CODE REVIEW

**Comment by mike-wendt** [comment]
@teju85 thanks, working on testing this build now. Automated PR testing isn't up for this repo yet, but I'll post a link to the manual test.

**Comment by teju85** [comment]
Thanks @mike-wendt for the reordering of packages. I had missed that one!

**Comment by mike-wendt** [comment]
✅ https://gpuci.gpuopenanalytics.com/job/rapidsai/job/conda/job/meta-pkgs/job/rapids-meta-pkg-nightly-test/5/ - passed all tests, will merge and cut a new version of these packages

**Comment by mike-wendt** [comment]
https://gpuci.gpuopenanalytics.com/job/rapidsai/job/conda/job/meta-pkgs/job/rapids-meta-pkg-nightly/32/ < new 0.14 pkgs with changes

**Pull request merged**
