### PR TITLE
bump cupy version to >=8.5.0

### PR DESCRIPTION
**Pull request by kkraus14**
Related to rapidsai/cudf#7615 to unblock Dask bugs that are fixed in cupy 8.5.0

### CODE REVIEW

**Review by mike-wendt — APPROVED** [review]

**Comment by kkraus14** [comment]
Looks like something got aborted?

**Comment by mike-wendt** [comment]
Builds were aborted due to a timeout with the CUDA 10.1 builds - I increased it to 20 mins from 15 mins

**Comment by mike-wendt** [comment]
rerun tests

**Comment by kkraus14** [comment]
@mike-wendt should we merge this? Should unblock cuDF CI and all of the other libraries have relaxed pinnings where this shouldn't cause any issues.

**Pull request merged**
