### PR TITLE
Add jupyter-packaging dependency

### PR DESCRIPTION
**Pull request by Ethyling**
Add jupyter-packaging dependency

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]

**Comment by Ethyling** [comment]
rerun tests

**Comment by Ethyling** [comment]
rerun tests

**Comment by Ethyling** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
since the relevant tests for this PR passed in CI, I am admin merging to unblock some things downstream. I have a message to the Blazing team to debug their related failures that we're seeing here.

**Pull request merged**
