### PR TITLE
Update to black 22.3.0.

### PR DESCRIPTION
**Pull request by vyasr**
We need the newest version of black to address https://github.com/psf/black/issues/2964

### CODE REVIEW

**Comment by vyasr** [comment]
rerun tests

**Comment by jakirkham** [comment]
rerun tests

**Comment by jakirkham** [comment]
Seeing the following error [on CI]( https://gpuci.gpuopenanalytics.com/job/rapidsai/job/integration/job/prb/job/meta-pkg-nightly-build/CONDA_CONFIG_FILE=conda%2Frecipes%2Fversions.yaml,CONDA_USERNAME=rapidsai-nightly,CUDA_VER=11.5,PYTHON_VER=3.8,RAPIDS_VER=22.06.00a/lastBuild/console ):

```
conda.exceptions.ResolvePackageNotFound: 
  - cuml=22.06
  - cugraph=22.06
  - libcugraph_etl=22.06
  - pylibcugraph=22.06
```

**Comment by vyasr** [comment]
@jakirkham I think so, was chatting with @ajschmidt8 about this issue offline and that fix should create the missing dependencies. I'll trigger tests again tomorrow, new packages should all definitely be out by then.

**Comment by jakirkham** [comment]
rerun tests

(new raft packages appear to be up)

**Comment by jakirkham** [comment]
rerun tests

**Comment by vyasr** [comment]
Thanks @jakirkham @ajschmidt8 for following up :) We're getting closer! It looks like the outstanding issues are cuxfilter related.

**Comment by ajschmidt8** [comment]
The relevant tests have passed for this PR, so I will admin merge it to keep it from holding things up.

**Pull request merged**
