### PR TITLE
Update branch-0.17

### PR DESCRIPTION
**Pull request by ajschmidt8**
This PR updates `branch-0.17` with the latest changes from `branch-0.16`.

### CODE REVIEW

**Comment by jakirkham** [comment]
Are the CI failures expected?

**Comment by mike-wendt** [comment]
```
conda.exceptions.ResolvePackageNotFound: 
xgboost=1.2.0dev.rapidsai0.17
```

I think in this transistion period we still use the 0.16 version of xgboost until we finalize it for 0.16 and cut 0.17

**Review by kkraus14 — APPROVED** [review]

**Comment by mike-wendt** [comment]
> ```
> conda.exceptions.ResolvePackageNotFound: 
> xgboost=1.2.0dev.rapidsai0.17
> ```
> 
> I think in this burndown period we still use the 0.16 version of xgboost until we finalize it for 0.16 and cut 0.17

Working on a fix in #143

**Comment by mike-wendt** [comment]
Closing this as we're not ready to cut a `branch-0.17` yet and we're building 0.16/0.17 from `branch-0.16` until code freeze next week

**Pull request closed without merging**
