### PR TITLE
Limit clang dependency for x86_64

### PR DESCRIPTION
**Pull request by Ethyling**
Clang is only used to check code format and format test will only be run on x86_64 (not arm64)

### CODE REVIEW

**Comment by Ethyling** [comment]
rerun tests

**Comment by Ethyling** [comment]
rerun tests

**Comment by Ethyling** [comment]
rerun tests

**Comment by Ethyling** [comment]
rerun tests

**Comment by Ethyling** [comment]
rerun tests

**Comment by Ethyling** [comment]
rerun tests

**Review by ajschmidt8 — APPROVED** [review]

**Comment by Ethyling** [comment]
rerun tests

**Comment by Ethyling** [comment]
rerun tests

**Comment by Ethyling** [comment]
rerun tests

**Pull request merged**
