### PR TITLE
Drop `nvstrings`

### PR DESCRIPTION
**Pull request by jakirkham**
cc @kkraus14

### CODE REVIEW

**Comment by mike-wendt** [comment]
PR testing will be fixed today, then we can see if it passes to approve. Working on the fixes in #55 first

**Comment by mike-wendt** [comment]
@jakirkham please pull `branch-0.15` for testing to work

**Comment by jakirkham** [comment]
Thanks Mike! 😄

I've pulled `rapidsai/branch-0.15` and merged it into this PR's branch. Please let me know if there is anything else we need here 🙂

**Comment by jakirkham** [comment]
Thanks all! 😄

**Pull request merged**
