### PR TITLE
Allow CuPy 9

### PR DESCRIPTION
**Pull request by jakirkham**
Relax the CuPy version constraint to allow CuPy 9 to be used as well.

### CODE REVIEW

**Review by ajschmidt8 — COMMENTED** [review]
It looks the libraries below are pinned to the old version spec. Should this change be tested with them before merging?

- https://github.com/rapidsai/cuxfilter/blob/branch-0.18/conda/recipes/cuxfilter/meta.yaml#L33
- https://github.com/rapidsai/cusignal/blob/branch-0.18/conda/recipes/cusignal/meta.yaml#L31
- https://github.com/rapidsai/cudf/blob/branch-0.18/conda/recipes/cudf/meta.yaml#L38
- https://github.com/rapidsai/cuml/blob/branch-0.18/conda/recipes/cuml/meta.yaml#L44

**Comment by jakirkham** [comment]
That makes sense and agree. Let's hold off on this for a bit then.

**Comment by ajschmidt8** [comment]
> That makes sense and agree. Let's hold off on this for a bit then.

@jakirkham, sounds good to me. do you want to close this PR or convert it to a draft in the meantime? This might help avoid some confusion because I see Dante is also changing the spec in https://github.com/rapidsai/cuml/pull/3378 (which will also need to be tested with all the repos).

**Comment by jakirkham** [comment]
Good point. Marked as draft. We can revisit once we are ready 🙂

**Comment by mike-wendt** [comment]
Should this be merged with #208 or the other way around?

**Comment by jakirkham** [comment]
Would do Dante's PR first. I think we can wait on this one for a bit. Happy to resolve conflicts here after that goes in.

**Comment by raydouglass** [comment]
@jakirkham What's the status of this?

**Comment by jakirkham** [comment]
CuPy has been releasing some betas (which we have packaged in conda-forge). These have seen some use already. The CuPy 9 RC is due out 25 March. CuPy 9 final is due out 22 April. More details here ( https://github.com/cupy/cupy/issues/3891 )

This is close to RAPIDS 0.19 release schedule though the fact that RAPIDS 0.19 is due out 15 April (a week before CuPy 9) could make things tricky if we want to include CuPy 9 in RAPIDS 0.19.

Here are some options:

1. We discuss with CuPy devs about bumping up their release to align with ours
2. We push out the RAPIDS release a week or so to line up with CuPy's
3. We hold off on this until RAPIDS 0.20

Thoughts? 🙂

**Comment by pentschev** [comment]
I would like to point out that CuPy is today maintained by only 3-4 people and they're very often working real hard (including weekends) when release dates are close, so if we want to align 0.19 and CuPy 9 I would suggest we try to align RAPIDS release to CuPy's to alleviate pressure on them.

**Comment by kkraus14** [comment]
> I would like to point out that CuPy is today maintained by only 3-4 people and they're very often working real hard (including weekends) when release dates are close, so if we want to align 0.19 and CuPy 9 I would suggest we try to align RAPIDS release to CuPy's to alleviate pressure on them.

RAPIDS 0.19 release is aligned to GTC so we cannot push it at this point.

**Comment by pentschev** [comment]
> RAPIDS 0.19 release is aligned to GTC so we cannot push it at this point.

Ok, then our alternatives are:

* We don't tie RAPIDS 0.19 to CuPy 9;
* We ask CuPy maintainers to release earlier because of GTC/RAPIDS 0.19 -- this will possibly require us to allocate a couple engineers in the 2-3 weeks before CuPy's release to help ensure everything goes smoothly.

We have a biweekly call with PFN next Tuesday, so it would be good if we have a decision on what to do by Monday early afternoon ET.

**Comment by jakirkham** [comment]
Do we know if PfN is presenting at GTC? Maybe they would be interested in releasing around the same time for the same reason

**Comment by pentschev** [comment]
> Do we know if PfN is presenting at GTC? Maybe they would be interested in releasing around the same time for the same reason

They've been offered to submit proposals, I don't know what happened to those, I'll check.

**Comment by pentschev** [comment]
I checked and there will only be an Optuna talk from PFN, no CuPy talks at GTC.

**Comment by pentschev** [comment]
Reminder that we have the CuPy biweekly meeting tomorrow with PFN. If we need to check whether CuPy 9 release can be done earlier to meet our needs, *please let me know by 3pm ET today* !

**Comment by ajschmidt8** [comment]
The below libraries have `cupy` pins that are `<9`. I think we'll want to get them updated before merging this PR so that we don't run into version conflicts in the containers.

- https://github.com/rapidsai/cuxfilter/blob/branch-0.20/conda/recipes/cuxfilter/meta.yaml#L33
- https://github.com/rapidsai/cudf/blob/branch-0.20/conda/recipes/cudf/meta.yaml#L39
- https://github.com/rapidsai/cuml/blob/branch-0.20/conda/recipes/cuml/meta.yaml#L44

`cusignal` has `<9.1` which should be fine, but may not hurt to update to `<10.0.0a0` also

- https://github.com/rapidsai/cusignal/blob/branch-0.20/conda/recipes/cusignal/meta.yaml#L31

**Comment by jakirkham** [comment]
Thanks AJ! 😄

Have submitted the following PRs to allow CuPy 9 to be use in the projects listed:

* https://github.com/rapidsai/cuxfilter/pull/275
* https://github.com/rapidsai/cudf/pull/8082
* https://github.com/rapidsai/cuml/pull/3798
* https://github.com/rapidsai/cusignal/pull/359

**Comment by jakirkham** [comment]
All of those PRs have passed 😄

Asking relevant teams for reviews

**Comment by jakirkham** [comment]
Looks like all of those PRs are now merged. Please let me know if there's anything else we need to do here 🙂

**Comment by ajschmidt8** [comment]
> Looks like all of those PRs are now merged. Please let me know if there's anything else we need to do here

@jakirkham, just updated the branch here. assuming CI succeeds again, we can go ahead and merge :+1:.

**Comment by jakirkham** [comment]
Looks like it passes! 🟢 😄 🎉

**Review by ajschmidt8 — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks AJ! 😄

**Pull request merged**
