### PR TITLE
Upgrade NCCL to 2.9.9

### PR DESCRIPTION
**Pull request by dantegd**
cc @rlratzel

### CODE REVIEW

**Review by Ethyling — APPROVED** [review]

**Review by rlratzel — APPROVED** [review]

**Comment by jakirkham** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
https://github.com/BlazingDB/blazingsql/pull/1559 should fix these failures

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by jakirkham** [comment]
Was just about to restart CI 😂

**Comment by ajschmidt8** [comment]
we still made some progress here despite the failures here. The `21.06` `meta-pkg-nightly` tests passed (`21.08` failed because of missing `xgboost`, but that's fine for now). I'll have to take a look at the integration tests in the morning.

**Comment by dantegd** [comment]
Thanks for the update @ajschmidt8, feel free to ping me when this is merge to merge the cuML one immediately thereafter. 

Thanks for the help everybody!!!

**Comment by ajschmidt8** [comment]
rerun tests

**Pull request merged**
