### PR TITLE
Require Dask + Distributed 2.22.0

### PR DESCRIPTION
**Pull request by jakirkham**
Needed for PR ( https://github.com/rapidsai/cudf/pull/5827 ).

cc @kkraus14 @quasiben

### CODE REVIEW

**Comment by ajschmidt8** [comment]
@jakirkham, it looks like CI is showing the error message below when trying to conda-build `rapids-build-env`.

https://gpuci.gpuopenanalytics.com/job/rapidsai/job/integration/job/prb/job/env-pkg-nightly-build/135/CONDA_CONFIG_FILE=conda%2Frecipes%2Fversions.yaml,CONDA_USERNAME=rapidsai-nightly,CUDA_VER=10.2,DEFAULT_CUDA_VER=10.1,PYTHON_VER=3.7,RAPIDS_VER=0.15/console

image

**Comment by kkraus14** [comment]
@ajschmidt8 `dask` is a `noarch` package since it's pure Python. Is that an issue?

**Comment by kkraus14** [comment]
rerun tests

**Comment by jakirkham** [comment]
Yeah I think it may not have been copied over to the RAPIDS CI mirror when I submitted the PR.

**Pull request merged**
