### PR TITLE
Add cuProj to the RAPIDS meta package

### PR DESCRIPTION
**Pull request by jarmak-nv**
Small PR to add `cuProj` to the RAPIDS metapackages.

Depends on https://github.com/rapidsai/cuspatial/pull/1217

### CODE REVIEW

**Review by raydouglass — APPROVED** [review]

**Comment by jakirkham** [comment]
It looks like the linked PR in the OP was merged

**Comment by jakirkham** [comment]
Would it be possible to restart CI?

**Comment by jakirkham** [comment]
Still seeing CI failures. Though they seem to be related to various conflicts (as opposed to missing packages)

**Comment by jakirkham** [comment]
Great, glad to see we got this worked out. Thanks all! 🙏

**Pull request merged**
