### PR TITLE
[REVIEW] Add libpq dependency

### PR DESCRIPTION
**Pull request by romulo-auccapuclla**
Changes:
* Add libpq dependency for blazing build env

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by ajschmidt8** [comment]
add to allowlist

**Review by ajschmidt8 — APPROVED** [review]

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
@romulo-auccapuclla, it's been a while since this PR has been opened so I just wanted to double-check that it's still needed. If it is, I will merge it once CI passes.

**Comment by ajschmidt8** [comment]
Closing this PR since Blazing is no longer included in RAPIDS containers

**Pull request closed without merging**
