### PR TITLE
Update `xgboost` requirement

### PR DESCRIPTION
**Pull request by jakirkham**
* Make sure to pull in the latest `xgboost` package (without the `__cuda` requirement)
* Drop `CONDA_OVERRIDE_CUDA`

### CODE REVIEW

**Review by raydouglass — APPROVED** [review]

**Review by bdice — APPROVED** [review]

**Comment by jakirkham** [comment]
CI failures are expected as we are waiting for [the `xgboost` package builds to finish]( https://github.com/rapidsai/xgboost-feedstock/actions/runs/5730890118 )

We can restart once those complete. Will keep an eye on them

**Comment by jakirkham** [comment]
Build failures are due overly strict pinnings in XGBoost packages downstream from `libxgboost`. Fixing with PR ( https://github.com/rapidsai/xgboost-feedstock/pull/16 )

Can follow up here after

**Comment by jakirkham** [comment]
Ok that fix is merged and [packages are building]( https://github.com/rapidsai/xgboost-feedstock/actions/runs/5732557502 )

Can restart here once they are up

**Comment by jakirkham** [comment]
New packages are built and up. Restarting CI

**Pull request merged**
