### PR TITLE
Update xgboost version

### PR DESCRIPTION
**Pull request by ajschmidt8**
This PR updates the `xgboost` version to match `cuml`'s version ([link](https://github.com/rapidsai/cuml/blob/branch-21.08/ci/gpu/build.sh#L58)).

### CODE REVIEW

**Review by raydouglass — APPROVED** [review]

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
The relevant tests have passed. admin merging.

**Pull request merged**
