### PR TITLE
Pin gdal to 3.2.x

### PR DESCRIPTION
**Pull request by weiji14**
Bump gdal from 3.1.x to 3.2.x, needed for https://github.com/rapidsai/cuspatial/pull/347. Supersedes #204.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Review by ajschmidt8 — APPROVED** [review]

**Comment by ajschmidt8** [comment]
ok to test

**Comment by ajschmidt8** [comment]
@weiji14, thank you for your contribution!

**Comment by weiji14** [comment]
Seems like there's some package conflicts. Among them:

```bash
08:37:56 Package gdal conflicts for:
08:37:56 gdal[version='>=3.2.0,<3.3.0a0']
08:37:56 geopandas[version='>=0.6,<=0.8.1'] -> fiona -> gdal[version='1.11.4|2.1.*|2.2.*|>=2.2.2,<2.3.0a0|>=2.2.4,<2.3.0a0|>=2.3.2,<2.4.0a0|>=2.4.0,<2.5.0a0|>=2.4.1,<2.5.0a0|>=2.4.2,<2.5.0a0|>=2.*']
```

There's actually a newer version of `geopandas=0.8.2` out at https://pypi.org/project/geopandas/0.8.2/, but not sure if it will fix the conflict.

**Comment by weiji14** [comment]
It's been about 2 weeks, could the tests be re-run please to see if the dependency conflict still exists?

**Comment by ajschmidt8** [comment]
rerun tests

**Review by kkraus14 — APPROVED** [review]

**Pull request merged**
