### PR TITLE
[REVIEW] Upgrade librdkafka to 1.5.0

### PR DESCRIPTION
**Pull request by kkraus14**
Following changes here: https://github.com/rapidsai/cudf/pull/6312

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]

**Comment by mike-wendt** [comment]
Blocked by rapidsai/cuml#2878

**Comment by mike-wendt** [comment]
Waiting on PR rapidsai/cuml#2882

**Comment by jakirkham** [comment]
Looks like the cuML PR has been merged and packages built. Let's give this another try...

rerun tests

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by kkraus14** [comment]
rerun tests

**Comment by jakirkham** [comment]
Thanks all! 😄

**Pull request merged**
