### PR TITLE
Bump geopandas to 0.11.0

### PR DESCRIPTION
**Pull request by thomcom**
This bump gets rid of a recurrent pytest warning message, in particular.

### CODE REVIEW

**Comment by ajschmidt8** [comment]
waiting to merge until https://github.com/rapidsai/cuspatial/pull/600 is merged.

**Comment by thomcom** [comment]
Actually please wait for #585 which #600 got this ops change from.

**Comment by ajschmidt8** [comment]
@thomcom, can I merge this now? Or do we need to wait for https://github.com/rapidsai/cuspatial/pull/600

**Comment by thomcom** [comment]
Please merge.

**Review by ajschmidt8 — APPROVED** [review]

**Pull request merged**
