### PR TITLE
Add sphinx-click to docs environment

### PR DESCRIPTION
**Pull request by charlesbluca**
Required for dask-cuda docs; see [rapidsai/dask-cuda#580 (comment)](https://github.com/rapidsai/dask-cuda/pull/580#discussion_r616034712)

### CODE REVIEW

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by charlesbluca** [comment]
Looks like the CI failure here is because of a timeout trying to access cuTENSOR:


```
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 474, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 463, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 208, in build
    return build_tree(absolute_recipes, config, stats, build_only=build_only, post=post,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2870, in build_tree
    test(pkg, config=metadata.config.copy(), stats=stats)
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2666, in test
    environ.create_env(metadata.config.test_prefix, actions, config=metadata.config,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/environ.py", line 875, in create_env
    execute_actions(actions, index)
  File "/opt/conda/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.8/site-packages/conda/plan.py", line 321, in execute_actions
    execute_instructions(plan, index, verbose)
  File "/opt/conda/lib/python3.8/site-packages/conda/plan.py", line 533, in execute_instructions
    cmd(state, arg)
  File "/opt/conda/lib/python3.8/site-packages/conda/instructions.py", line 67, in PROGRESSIVEFETCHEXTRACT_CMD
    progressive_fetch_extract.execute()
  File "/opt/conda/lib/python3.8/site-packages/conda/core/package_cache_data.py", line 655, in execute
    raise CondaMultiError(exceptions)
conda.CondaMultiError: HTTP 504 GATEWAY TIME-OUT for url <https://conda.anaconda.org/conda-forge/linux-64/cutensor-1.2.2.5-h96e36e3_3.tar.bz2>
Elapsed: 01:00.007072

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

**Comment by ajschmidt8** [comment]
> Looks like the failure here is because of a timeout trying to access cuTENSOR:

ah yeah, that looks like a 504 error from conda's servers. have to rerun tests unforunately

**Comment by charlesbluca** [comment]
Are there issues with conda's servers? This 504 seesm to be happening for a lot of packages

**Comment by ajschmidt8** [comment]
it's possible. I have to update your branch here before it merges which will re-trigger CI again. so hopefully we don't get any 504s this time.

**Review by ajschmidt8 — APPROVED** [review]

**Comment by charlesbluca** [comment]
Is this good to merge?

**Pull request merged**
