### PR TITLE
Upgrade arrow to 8

### PR DESCRIPTION
**Pull request by galipremsagar**
Required for: https://github.com/rapidsai/cudf/pull/10816

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]
Approved. Pending successful CI completion.

**Comment by vyasr** [comment]
rerun tests

**Comment by galipremsagar** [comment]
rerun tests

**Comment by galipremsagar** [comment]
rerun tests

**Comment by galipremsagar** [comment]
rerun tests

**Pull request merged**
