### PR TITLE
Update scikit-learn to 0.24

### PR DESCRIPTION
**Pull request by dantegd**
Depends on https://github.com/rapidsai/cuml/pull/4205 so cuML is not blocked, updates Scikit-learn to the latest official release.

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]

**Comment by dantegd** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
Hmm. It looks like there is a long stack trace [here](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/integration/job/prb/job/meta-pkg-nightly-build/732/CONDA_CONFIG_FILE=conda%2Frecipes%2Fversions.yaml,CONDA_USERNAME=rapidsai-nightly,CUDA_VER=11.4,PYTHON_VER=3.7,RAPIDS_VER=21.10.00a/console) for the `meta-pkg-nightly` failures related to `cugraph`. I haven't seen this before. Any thoughts @dantegd? If not, we might need to consult the graph team.

**Comment by dantegd** [comment]
rerun tests

**Comment by jakirkham** [comment]
Should be addressed by PR ( https://github.com/rapidsai/gpuci-build-environment/pull/209 )

**Comment by dantegd** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
you'll need to wait until these images are updated: https://hub.docker.com/r/gpuci/miniconda-cuda-driver

shouldn't be too long.

**Comment by dantegd** [comment]
It seems that it is now cuspatial the one that is failing ☹️ : 

```python

Traceback (most recent call last):
  File "/opt/conda/conda-bld/rapids_1631824037386/test_tmp/run_test.py", line 14, in <module>
    import cuspatial
  File "/opt/conda/conda-bld/rapids_1631824037386/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/cuspatial/__init__.py", line 2, in <module>
    from .core import interpolate
  File "/opt/conda/conda-bld/rapids_1631824037386/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/cuspatial/core/interpolate.py", line 8, in <module>
    from cuspatial._lib.interpolate import (
  File "cuspatial/_lib/interpolate.pyx", line 1, in init cuspatial._lib.interpolate
ValueError: cudf._lib.table.Table size changed, may indicate binary incompatibility. Expected 32 from C header, got 24 from PyObject
```

**Comment by jakirkham** [comment]
Is it possible that CI run was just in-between Conda package build/uploads for those libraries?

**Comment by dantegd** [comment]
It is always possible that was the case, so will rerun tests to be sure

**Comment by dantegd** [comment]
rerun tests

**Comment by jakirkham** [comment]
rerun tests

**Comment by jakirkham** [comment]
Yeah we are still see that issue. Wondering if we can trigger a rebuild of that package?

**Comment by ajschmidt8** [comment]
seems like this `cuspatial` PR may need to be merged first: https://github.com/rapidsai/cuspatial/pull/449

**Comment by jakirkham** [comment]
Good catch AJ. Prodded the CI over there to see if that would clear things up

**Comment by vyasr** [comment]
rerun tests

**Comment by vyasr** [comment]
rerun tests

**Comment by vyasr** [comment]
It looks like these builds depend on prebuilt conda packages. The tests are failing because of an ABI incompatibility that should be resolved by getting the newest builds of cuspatial. I guess we need to wait for the newest cuspatial nightlies to resolve that problem?

**Comment by jakirkham** [comment]
Yeah exactly, but that's ok. We can keep an eye on things and prod this again when they come through 🙂

Thanks for resolving the underlying issue Vyas! 😄

**Comment by ajschmidt8** [comment]
Looks like they were just published:https://anaconda.org/rapidsai-nightly/cuspatial/files

Let's try one more time.

rerun tests

**Comment by ajschmidt8** [comment]
is this ready to be merged now? @dantegd, @jakirkham

**Comment by jakirkham** [comment]
Thanks Dante & AJ! 😄

**Pull request merged**
