### PR TITLE
close open-ended pins for cuxfilter dependencies

### PR DESCRIPTION
**Pull request by AjayThorve**
updated version pins for bokeh, panel, geopandas, pyproj, pydeck, datashader

### CODE REVIEW

**Review by raydouglass — APPROVED** [review]

**Review by ajschmidt8 — CHANGES_REQUESTED** [review]
@AjayThorve, thanks for knocking this out. Can you also add a version pin for `pyppeteer` in the line below?

https://github.com/rapidsai/integration/blob/branch-0.17/conda/recipes/rapids-build-env/meta.yaml#L112

**Comment by AjayThorve** [comment]
> @AjayThorve, thanks for knocking this out. Can you also add a version pin for `pyppeteer` in the line below?
> 
> https://github.com/rapidsai/integration/blob/branch-0.17/conda/recipes/rapids-build-env/meta.yaml#L112

@ajschmidt8, I added it

**Comment by mike-wendt** [comment]
Asking @dillon-cullinan to help diagnose the test failures in the meta pkg for blazing. There may be a conflict and I want to see if it is due to these pins or something known

**Review by ajschmidt8 — APPROVED** [review]

**Comment by mike-wendt** [comment]
Looks like this is a Blazing issue, but lets wait until it is fixed to merge this to be sure

**Comment by dillon-cullinan** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Pull request merged**
