### PR TITLE
Add `mock` package to `rapids-build-env`

### PR DESCRIPTION
**Pull request by ajschmidt8**
This PR adds the `mock` package to `rapids-build-env`. `mock` used to be included by the `moto` package, but the `moto` package was recently upgraded and removed its dependency on `mock` which caused some issues for `cuxfilter`. So we need to include `mock` explicitly.

### CODE REVIEW

**Review by Ethyling — APPROVED** [review]

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
The `meta-pkg-nightly` tests need to pass before this PR can be merged. Currently there are some conda solver issues. The PR below may help solve some of the current solve issues. Once the changes from that PR are published, we should run the tests again here.

- https://github.com/rapidsai/cudf/pull/9749

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
Now we're waiting on the PR below. Once that PR is merged and the new `cucim` packages go out, we can run the tests again here.

https://github.com/rapidsai/cucim/pull/164

**Comment by ajschmidt8** [comment]
Woo! Everything solves correctly now. Merging.

**Pull request merged**
