### PR TITLE
[REVIEW] Pinning black, flake8 and isort

### PR DESCRIPTION
**Pull request by rgsl888prabhu**
black, flake8 and isort are not controlled by their versions. And sometimes these break and block CIs. So planning to control the version of these to ensure smooth CI operation.

It is open for review, but as this will affect all the RAPIDS projects, wanted to check with PICs of those projects if they have any concerns or any other approach to handle this issue.

### CODE REVIEW

**Comment by mike-wendt** [comment]
@rgsl888prabhu looks like there are conflicts with `branch-0.15`, can you resolve them so we can review?

I'm pulling in @jakirkham @jrhemstad @kkraus14 for reviewers to this as well

**Comment by jakirkham** [comment]
Would suggest we relax the pinnings a bit and pin to major versions instead.

**Comment by rgsl888prabhu** [comment]
> Would suggest we relax the pinnings a bit and pin to major versions instead.

If we pin to major version, pkg will still get update for any new minor versions, which might create similar problems we have been facing.

**Comment by jakirkham** [comment]
The problem we saw with `black` was due to it upgrading to `5.0`. Major versions can and do break compatibility. What I'm proposing takes that into account.

**Comment by kkraus14** [comment]
FWIW we've also consistently seen breakages with flake8 minor version releases

**Comment by jakirkham** [comment]
Could you please share some examples?

**Comment by kkraus14** [comment]
> Could you please share some examples?

Going from 3.7 --> 3.8: https://github.com/rapidsai/cudf/pull/5185
Don't remember the specific version change: https://github.com/rapidsai/cudf/pull/821/files

**Comment by jakirkham** [comment]
Thanks! If we want to pin `flake8` to minor version and let the patch version float, that seems fine.

**Pull request merged**
