### PR TITLE
Update to XGBoost 2

### PR DESCRIPTION
**Pull request by jakirkham**
Updates the XGBoost constraint to the newer XGBoost 2.

### CODE REVIEW

**Review by raydouglass — APPROVED** [review]

**Comment by jakirkham** [comment]
The install failure seen here will be fixed with PR ( https://github.com/rapidsai/xgboost-feedstock/pull/49 )

**Comment by jakirkham** [comment]
The above PR has been merged and packages have shipped. Restarting CI

**Comment by jakirkham** [comment]
This is now passing! 🎉

**Pull request merged**
