### PR TITLE
Upgrade to cupy 11

### PR DESCRIPTION
**Pull request by galipremsagar**
Required for https://github.com/rapidsai/cudf/pull/11449#pullrequestreview-1085735332

### CODE REVIEW

**Comment by ajschmidt8** [comment]
@galipremsagar, from my `cupy` search below, it seems that this change will need to be coordinated across several repositories. can you coordinate this upgrade?

- search: https://github.com/search?l=YAML&p=1&q=org%3Arapidsai+cupy&type=Code
- https://github.com/rapidsai/cuxfilter/blob/branch-22.10/conda/environments/cuxfilter_dev_cuda11.4.yml#L10
- https://github.com/rapidsai/cucim/blob/branch-22.10/conda/recipes/cucim/meta.yaml#L41
- https://github.com/rapidsai/cusignal/blob/branch-22.10/conda/recipes/cusignal/meta.yaml#L37
- https://github.com/rapidsai/cuml/blob/branch-22.10/conda/recipes/cuml/meta.yaml#L55
- https://github.com/rapidsai/kvikio/blob/branch-22.10/conda/environments/kvikio_dev_cuda11.5.yml#L14

**Comment by galipremsagar** [comment]
> @galipremsagar, from my `cupy` search below, it seems that this change will need to be coordinated across several repositories. can you coordinate this upgrade?
> 
> * search: https://github.com/search?l=YAML&p=1&q=org%3Arapidsai+cupy&type=Code
> * https://github.com/rapidsai/cuxfilter/blob/branch-22.10/conda/environments/cuxfilter_dev_cuda11.4.yml#L10
> * https://github.com/rapidsai/cucim/blob/branch-22.10/conda/recipes/cucim/meta.yaml#L41
> * https://github.com/rapidsai/cusignal/blob/branch-22.10/conda/recipes/cusignal/meta.yaml#L37
> * https://github.com/rapidsai/cuml/blob/branch-22.10/conda/recipes/cuml/meta.yaml#L55
> * https://github.com/rapidsai/kvikio/blob/branch-22.10/conda/environments/kvikio_dev_cuda11.5.yml#L14

Sure

**Comment by galipremsagar** [comment]
rerun tests

**Comment by jakirkham** [comment]
Thanks for refreshing these Prem! 🙏

**Comment by ajschmidt8** [comment]
rerun tests

**Review by ajschmidt8 — APPROVED** [review]

**Pull request merged**
