### PR TITLE
Bump librdkafka version to 1.7.*

### PR DESCRIPTION
**Pull request by jdye64**

### CODE REVIEW

**Comment by jdye64** [comment]
rerun tests

**Comment by jdye64** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
@jdye64, I wouldn't worry too much about the failures here. There's still a lot in flux with the `11.5` packages.

Ping me when this PR is ready to merge and I'll look at CI to see if the relevant tests have passed and admin merge this PR.

**Comment by jdye64** [comment]
rerun tests

**Comment by jdye64** [comment]
rerun tests

**Comment by jdye64** [comment]
rerun tests

**Comment by jdye64** [comment]
rerun tests

**Comment by jdye64** [comment]
rerun tests

**Comment by jdye64** [comment]
rerun tests

**Comment by jdye64** [comment]
rerun tests

**Comment by jdye64** [comment]
rerun tests

**Comment by jdye64** [comment]
rerun tests

**Comment by jdye64** [comment]
sorry, had accidentally closed

**Review by ajschmidt8 — APPROVED** [review]

**Comment by ajschmidt8** [comment]
https://github.com/rapidsai/cudf/pull/9486 is passing with new versions. Merging this PR.

**Pull request merged**
