### PR TITLE
Upgrade to Treelite 2.2.1

### PR DESCRIPTION
**Pull request by hcho3**
Required by rapidsai/cuml#4484. See the CI result in rapidsai/cuml#4484 which is testing cuML with Treelite 2.2.0.

EDIT. Using 2.2.1 patch release, to incorporate a hotfix (dmlc/treelite#340).

### CODE REVIEW

**Comment by hcho3** [comment]
Rerun tests

**Comment by hcho3** [comment]
Rerun tests

**Comment by hcho3** [comment]
rerun tests

**Comment by hcho3** [comment]
Rerun tests

**Comment by hcho3** [comment]
Rerun tests

**Comment by hcho3** [comment]
rerun tests

**Comment by hcho3** [comment]
@ajschmidt8 Can you help with the failing meta-pkg-nightly?

**Comment by ajschmidt8** [comment]
> @ajschmidt8 Can you help with the failing meta-pkg-nightly?

Looking now

**Comment by ajschmidt8** [comment]
> > @ajschmidt8 Can you help with the failing meta-pkg-nightly?
> 
> Looking now

Based on the stack trace that's in those logs, I've reached out to some people on the `cugraph` and `ucx` teams for some additional guidance here.

**Comment by ajschmidt8** [comment]
@hcho3, there is a PR below to address this issue.

- https://github.com/rapidsai/ucx-py/pull/830

**Comment by ajschmidt8** [comment]
rerun tests

**Comment by hcho3** [comment]
rerun tests

**Comment by hcho3** [comment]
rerun tests

**Comment by hcho3** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
The latest errors will be fixed once this PR is merged/deployed.

- https://github.com/rapidsai/cugraph/pull/2029

**Comment by hcho3** [comment]
Rerun tests

**Comment by hcho3** [comment]
Rerun tests

**Comment by hcho3** [comment]
Can we merge this?

**Review by ajschmidt8 — APPROVED** [review]

**Pull request merged**
