### PR TITLE
[REVIEW] FIX Add 21.08 nightly builds for burndown

### PR DESCRIPTION
**Pull request by dillon-cullinan**
Adds 21.08 nightly builds for burndown.

### CODE REVIEW

**Review by Ethyling — APPROVED** [review]

**Review by ajschmidt8 — APPROVED** [review]

**Comment by dillon-cullinan** [comment]
Do we know the cause of these errors for meta packages?

**Comment by jakirkham** [comment]
Think these issues may have been cleared out during the day. Going to give CI a nudge

rerun tests

**Comment by jakirkham** [comment]
That's new. Appears there are some missing symbol errors. One with cuDF and one with cuGraph. Mentioned both on Slack to see if anyone else knows about these

**Comment by jakirkham** [comment]
rerun tests

**Comment by jakirkham** [comment]
Think we are safe to try again

rerun tests

**Comment by jakirkham** [comment]
Ok so the 21.06 tests appear to have passed

Appears we are missing xgboost packages for 21.08

**Comment by ajschmidt8** [comment]
closing in favor of #285

**Pull request closed without merging**
