### PR TITLE
Bump Dask + Distributed to 2.23.0

### PR DESCRIPTION
**Pull request by jakirkham**
Includes this serialization performance improvement ( https://github.com/dask/distributed/pull/4004 ) amongst other things.

### CODE REVIEW

**Comment by mike-wendt** [comment]
@jakirkham can you review https://gpuci.gpuopenanalytics.com/job/rapidsai/job/integration/job/prb/job/meta-pkg-nightly-build/193/ and see why the 0.16 builds are not conda solving?

**Comment by jakirkham** [comment]
So I tried creating an environment with `rapids=0.16` locally and it looks like `dask` and `distributed` version `2.23.0` get pulled in.

<details>

```
$ conda create -n tst -c rapidsai-nightly rapids=0.16 python=3 cudatoolkit=10.2
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /datasets/jkirkham/miniconda/envs/tst

  added / updated specs:
    - cudatoolkit=10.2
    - python=3
    - rapids=0.16


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |      conda_forge           3 KB  conda-forge
    _openmp_mutex-4.5          |            1_gnu          22 KB  conda-forge
    arrow-cpp-proc-1.0.0       |             cuda          20 KB  conda-forge
    dask-xgboost-0.2.0.dev28   |   cuda10.2py38_0          18 KB  rapidsai-nightly
    faiss-proc-1.0.0           |             cuda          18 KB  rapidsai-nightly
    importlib_metadata-1.7.0   |                0           3 KB  conda-forge
    libblas-3.8.0              |      17_openblas          11 KB  conda-forge
    libcblas-3.8.0             |      17_openblas          11 KB  conda-forge
    liblapack-3.8.0            |      17_openblas          11 KB  conda-forge
    parquet-cpp-1.5.1          |                2           3 KB  conda-forge
    pthread-stubs-0.4          |    h14c3975_1001           5 KB  conda-forge
    python_abi-3.8             |           1_cp38           4 KB  conda-forge
    ucx-1.8.1+g6b29558         |       ha5db111_0         8.5 MB  rapidsai-nightly
    wheel-0.35.0               |     pyh9f0ad1d_0          23 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         8.6 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_gnu
  abseil-cpp         conda-forge/linux-64::abseil-cpp-20200225.2-he1b5a44_2
  aiohttp            conda-forge/linux-64::aiohttp-3.6.2-py38h516909a_0
  appdirs            conda-forge/noarch::appdirs-1.4.3-py_1
  argon2-cffi        conda-forge/linux-64::argon2-cffi-20.1.0-py38h1e0a361_1
  arrow-cpp          conda-forge/linux-64::arrow-cpp-0.17.1-py38h1234567_11_cuda
  arrow-cpp-proc     conda-forge/linux-64::arrow-cpp-proc-1.0.0-cuda
  async-timeout      conda-forge/noarch::async-timeout-3.0.1-py_1000
  attrs              conda-forge/noarch::attrs-19.3.0-py_0
  aws-sdk-cpp        conda-forge/linux-64::aws-sdk-cpp-1.7.164-hba45d7a_2
  backcall           conda-forge/noarch::backcall-0.2.0-pyh9f0ad1d_0
  backports          conda-forge/noarch::backports-1.0-py_2
  backports.functoo~ conda-forge/noarch::backports.functools_lru_cache-1.6.1-py_0
  bleach             conda-forge/noarch::bleach-3.1.5-pyh9f0ad1d_0
  blosc              conda-forge/linux-64::blosc-1.20.0-he1b5a44_0
  bokeh              conda-forge/linux-64::bokeh-2.1.1-py38h32f6830_0
  boost              conda-forge/linux-64::boost-1.72.0-py38h9de70de_0
  boost-cpp          conda-forge/linux-64::boost-cpp-1.72.0-h8e57a91_0
  brotli             conda-forge/linux-64::brotli-1.0.7-he1b5a44_1004
  brotlipy           conda-forge/linux-64::brotlipy-0.7.0-py38h1e0a361_1000
  brunsli            conda-forge/linux-64::brunsli-0.1-he1b5a44_0
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h516909a_2
  c-ares             conda-forge/linux-64::c-ares-1.16.1-h516909a_0
  ca-certificates    conda-forge/linux-64::ca-certificates-2020.6.20-hecda079_0
  cairo              conda-forge/linux-64::cairo-1.16.0-hcf35c78_1003
  certifi            conda-forge/linux-64::certifi-2020.6.20-py38h32f6830_0
  cffi               conda-forge/linux-64::cffi-1.14.1-py38h5bae8af_0
  cfitsio            conda-forge/linux-64::cfitsio-3.470-hce51eda_6
  chardet            conda-forge/linux-64::chardet-3.0.4-py38h32f6830_1006
  charls             conda-forge/linux-64::charls-2.1.0-he1b5a44_2
  click              conda-forge/noarch::click-7.1.2-pyh9f0ad1d_0
  click-plugins      conda-forge/noarch::click-plugins-1.1.1-py_0
  cligj              conda-forge/noarch::cligj-0.5.0-py_0
  cloudpickle        conda-forge/noarch::cloudpickle-1.5.0-py_0
  colorcet           conda-forge/noarch::colorcet-2.0.1-py_0
  cryptography       conda-forge/linux-64::cryptography-3.0-py38h766eaa4_0
  cudatoolkit        pkgs/main/linux-64::cudatoolkit-10.2.89-hfd86e86_1
  cudf               rapidsai-nightly/linux-64::cudf-0.16.0a200814-py38_g5041a29a6_644
  cudf_kafka         rapidsai-nightly/linux-64::cudf_kafka-0.16.0a200814-py38_g5041a29a6_644
  cudnn              pkgs/main/linux-64::cudnn-7.6.5-cuda10.2_0
  cugraph            rapidsai-nightly/linux-64::cugraph-0.16.0a200814-py38_g3cacd9a0_193
  cuml               rapidsai-nightly/linux-64::cuml-0.16.0a200812-cuda10.2_py38_g4c1136ee1_229
  cupy               conda-forge/linux-64::cupy-7.7.0-py38hb1193b0_0
  curl               conda-forge/linux-64::curl-7.71.1-he644dc0_4
  cusignal           rapidsai-nightly/noarch::cusignal-0.16.0a200814-py38_gc3cce02_33
  cuspatial          rapidsai-nightly/linux-64::cuspatial-0.16.0a200814-py38_g88c27b3_7
  custreamz          rapidsai-nightly/linux-64::custreamz-0.16.0a200814-py38_g5041a29a6_644
  cuxfilter          rapidsai-nightly/linux-64::cuxfilter-0.16.0a200814-py38_gb1d1b6e_15
  cycler             conda-forge/noarch::cycler-0.10.0-py_2
  cyrus-sasl         conda-forge/linux-64::cyrus-sasl-2.1.27-h063b49f_1
  cytoolz            conda-forge/linux-64::cytoolz-0.10.1-py38h516909a_0
  dask               conda-forge/noarch::dask-2.23.0-py_0
  dask-core          conda-forge/noarch::dask-core-2.23.0-py_0
  dask-cuda          rapidsai-nightly/linux-64::dask-cuda-0.16.0a200814-py38_38
  dask-cudf          rapidsai-nightly/linux-64::dask-cudf-0.16.0a200814-py38_g5041a29a6_644
  dask-xgboost       rapidsai-nightly/noarch::dask-xgboost-0.2.0.dev28-cuda10.2py38_0
  datashader         conda-forge/noarch::datashader-0.10.0-py_0
  datashape          conda-forge/noarch::datashape-0.5.4-py_1
  decorator          conda-forge/noarch::decorator-4.4.2-py_0
  defusedxml         conda-forge/noarch::defusedxml-0.6.0-py_0
  distributed        conda-forge/linux-64::distributed-2.23.0-py38h32f6830_0
  dlpack             conda-forge/linux-64::dlpack-0.3-he1b5a44_1
  double-conversion  conda-forge/linux-64::double-conversion-3.1.5-he1b5a44_2
  entrypoints        conda-forge/linux-64::entrypoints-0.3-py38h32f6830_1001
  expat              conda-forge/linux-64::expat-2.2.9-he1b5a44_2
  faiss-proc         rapidsai-nightly/linux-64::faiss-proc-1.0.0-cuda
  fastavro           conda-forge/linux-64::fastavro-0.24.0-py38h1e0a361_0
  fastrlock          conda-forge/linux-64::fastrlock-0.5-py38h950e882_0
  fiona              conda-forge/linux-64::fiona-1.8.13-py38h033e0f6_1
  fontconfig         conda-forge/linux-64::fontconfig-2.13.1-h86ecdb6_1001
  freetype           conda-forge/linux-64::freetype-2.10.2-he06d7ca_0
  freexl             conda-forge/linux-64::freexl-1.0.5-h516909a_1002
  fsspec             conda-forge/noarch::fsspec-0.8.0-py_0
  gdal               conda-forge/linux-64::gdal-3.0.4-py38h172510d_10
  geopandas          conda-forge/noarch::geopandas-0.8.1-py_0
  geos               conda-forge/linux-64::geos-3.8.1-he1b5a44_0
  geotiff            conda-forge/linux-64::geotiff-1.6.0-h05acad5_0
  gettext            conda-forge/linux-64::gettext-0.19.8.1-hc5be6a0_1002
  gflags             conda-forge/linux-64::gflags-2.2.2-he1b5a44_1004
  giflib             conda-forge/linux-64::giflib-5.2.1-h516909a_2
  glib               conda-forge/linux-64::glib-2.65.0-h6f030ca_0
  glog               conda-forge/linux-64::glog-0.4.0-h49b9bf7_3
  grpc-cpp           conda-forge/linux-64::grpc-cpp-1.30.2-heedbac9_0
  hdf4               conda-forge/linux-64::hdf4-4.2.13-hf30be14_1003
  hdf5               conda-forge/linux-64::hdf5-1.10.6-nompi_h3c11f04_101
  heapdict           conda-forge/noarch::heapdict-1.0.1-py_0
  icu                conda-forge/linux-64::icu-64.2-he1b5a44_1
  idna               conda-forge/noarch::idna-2.10-pyh9f0ad1d_0
  imagecodecs        conda-forge/linux-64::imagecodecs-2020.5.30-py38h36e1e94_2
  imageio            conda-forge/noarch::imageio-2.9.0-py_0
  importlib-metadata conda-forge/linux-64::importlib-metadata-1.7.0-py38h32f6830_0
  importlib_metadata conda-forge/noarch::importlib_metadata-1.7.0-0
  ipykernel          conda-forge/linux-64::ipykernel-5.3.4-py38h23f93f0_0
  ipython            conda-forge/linux-64::ipython-7.17.0-py38h1cdfbd6_0
  ipython_genutils   conda-forge/noarch::ipython_genutils-0.2.0-py_1
  ipywidgets         conda-forge/noarch::ipywidgets-7.5.1-py_0
  jedi               conda-forge/linux-64::jedi-0.17.2-py38h32f6830_0
  jinja2             conda-forge/noarch::jinja2-2.11.2-pyh9f0ad1d_0
  joblib             conda-forge/noarch::joblib-0.16.0-py_0
  jpeg               conda-forge/linux-64::jpeg-9d-h516909a_0
  json-c             conda-forge/linux-64::json-c-0.13.1-hbfbb72e_1002
  jsonschema         conda-forge/linux-64::jsonschema-3.2.0-py38h32f6830_1
  jupyter-server-pr~ conda-forge/noarch::jupyter-server-proxy-1.5.0-py_0
  jupyter_client     conda-forge/noarch::jupyter_client-6.1.6-py_0
  jupyter_core       conda-forge/linux-64::jupyter_core-4.6.3-py38h32f6830_1
  jxrlib             conda-forge/linux-64::jxrlib-1.1-h516909a_2
  kealib             conda-forge/linux-64::kealib-1.4.13-h33137a7_1
  kiwisolver         conda-forge/linux-64::kiwisolver-1.2.0-py38hbf85e49_0
  krb5               conda-forge/linux-64::krb5-1.17.1-hfafb76e_2
  lcms2              conda-forge/linux-64::lcms2-2.11-hbd6801e_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.34-hc38a660_9
  lerc               conda-forge/linux-64::lerc-2.2-he1b5a44_0
  libaec             conda-forge/linux-64::libaec-1.0.4-he1b5a44_1
  libblas            conda-forge/linux-64::libblas-3.8.0-17_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-17_openblas
  libcudf            rapidsai-nightly/linux-64::libcudf-0.16.0a200814-cuda10.2_g5041a29a6_644
  libcudf_kafka      rapidsai-nightly/linux-64::libcudf_kafka-0.16.0a200814-g5041a29a6_644
  libcugraph         rapidsai-nightly/linux-64::libcugraph-0.16.0a200814-cuda10.2_g3cacd9a0_193
  libcuml            rapidsai-nightly/linux-64::libcuml-0.16.0a200812-cuda10.2_g4c1136ee1_229
  libcumlprims       rapidsai-nightly/linux-64::libcumlprims-0.15.0a200720-cuda10.2_57
  libcurl            conda-forge/linux-64::libcurl-7.71.1-hcdd3856_4
  libcuspatial       rapidsai-nightly/linux-64::libcuspatial-0.16.0a200814-cuda10.2_g88c27b3_7
  libdap4            conda-forge/linux-64::libdap4-3.20.6-h1d1bd15_1
  libedit            conda-forge/linux-64::libedit-3.1.20191231-h46ee950_1
  libev              conda-forge/linux-64::libev-4.33-h516909a_0
  libevent           conda-forge/linux-64::libevent-2.1.10-hcdb4288_1
  libfaiss           conda-forge/linux-64::libfaiss-1.6.3-he61ee18_1_cuda
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1007
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.3.0-h24d8f2e_14
  libgcrypt          conda-forge/linux-64::libgcrypt-1.8.4-hf484d3e_1000
  libgdal            conda-forge/linux-64::libgdal-3.0.4-he6a97d6_10
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.5.0-hdf63c60_14
  libgomp            conda-forge/linux-64::libgomp-9.3.0-h24d8f2e_14
  libgpg-error       conda-forge/linux-64::libgpg-error-1.36-he1b5a44_0
  libgsasl           conda-forge/linux-64::libgsasl-1.8.0-2
  libhwloc           conda-forge/linux-64::libhwloc-2.1.0-h3c4fd83_0
  libiconv           conda-forge/linux-64::libiconv-1.15-h516909a_1006
  libkml             conda-forge/linux-64::libkml-1.3.0-hb574062_1011
  liblapack          conda-forge/linux-64::liblapack-3.8.0-17_openblas
  libllvm9           conda-forge/linux-64::libllvm9-9.0.1-he513fc3_1
  libnetcdf          conda-forge/linux-64::libnetcdf-4.7.4-nompi_h84807e1_105
  libnghttp2         conda-forge/linux-64::libnghttp2-1.41.0-hab1572f_1
  libntlm            conda-forge/linux-64::libntlm-1.4-h516909a_1002
  libopenblas        conda-forge/linux-64::libopenblas-0.3.10-pthreads_hb3c22a3_4
  libpng             conda-forge/linux-64::libpng-1.6.37-hed695b0_2
  libpq              conda-forge/linux-64::libpq-12.3-h5513abc_0
  libprotobuf        conda-forge/linux-64::libprotobuf-3.12.4-h8b12597_0
  librdkafka         conda-forge/linux-64::librdkafka-1.4.0-h40bdf00_0
  librmm             rapidsai-nightly/linux-64::librmm-0.16.0a200814-cuda10.2_gd8ad1eb_194
  libsodium          conda-forge/linux-64::libsodium-1.0.18-h516909a_0
  libspatialindex    conda-forge/linux-64::libspatialindex-1.9.3-he1b5a44_3
  libspatialite      conda-forge/linux-64::libspatialite-4.3.0a-h2482549_1038
  libssh2            conda-forge/linux-64::libssh2-1.9.0-hab1572f_5
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.3.0-hdf63c60_14
  libtiff            conda-forge/linux-64::libtiff-4.1.0-hc7e4089_6
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000
  libuv              conda-forge/linux-64::libuv-1.34.0-h516909a_0
  libwebp            conda-forge/linux-64::libwebp-1.1.0-h56121f0_4
  libwebp-base       conda-forge/linux-64::libwebp-base-1.1.0-h516909a_3
  libxcb             conda-forge/linux-64::libxcb-1.13-h14c3975_1002
  libxgboost         rapidsai-nightly/linux-64::libxgboost-1.1.0dev.rapidsai0.15-cuda10.2_1
  libxml2            conda-forge/linux-64::libxml2-2.9.10-hee79883_0
  libzopfli          conda-forge/linux-64::libzopfli-1.0.3-he1b5a44_0
  llvmlite           conda-forge/linux-64::llvmlite-0.33.0-py38h4f45e52_1
  locket             conda-forge/noarch::locket-0.2.0-py_2
  lz4-c              conda-forge/linux-64::lz4-c-1.9.2-he1b5a44_1
  markdown           conda-forge/noarch::markdown-3.2.2-py_0
  markupsafe         conda-forge/linux-64::markupsafe-1.1.1-py38h1e0a361_1
  matplotlib-base    conda-forge/linux-64::matplotlib-base-3.3.1-py38h91b0d89_0
  mistune            conda-forge/linux-64::mistune-0.8.4-py38h1e0a361_1001
  msgpack-python     conda-forge/linux-64::msgpack-python-1.0.0-py38hbf85e49_1
  multidict          conda-forge/linux-64::multidict-4.7.5-py38h1e0a361_1
  multipledispatch   conda-forge/noarch::multipledispatch-0.6.0-py_0
  munch              conda-forge/noarch::munch-2.5.0-py_0
  nbconvert          conda-forge/linux-64::nbconvert-5.6.1-py38h32f6830_1
  nbformat           conda-forge/noarch::nbformat-5.0.7-py_0
  nccl               conda-forge/linux-64::nccl-2.5.7.1-hc6a2c23_0
  ncurses            conda-forge/linux-64::ncurses-6.2-he1b5a44_1
  networkx           conda-forge/noarch::networkx-2.4-py_1
  nodejs             conda-forge/linux-64::nodejs-13.13.0-hf5d1a2b_0
  notebook           conda-forge/linux-64::notebook-6.1.3-py38h32f6830_0
  numba              conda-forge/linux-64::numba-0.50.1-py38hcb8c335_1
  numpy              conda-forge/linux-64::numpy-1.19.1-py38h8854b6b_0
  olefile            conda-forge/noarch::olefile-0.46-py_0
  openjpeg           conda-forge/linux-64::openjpeg-2.3.1-h981e76c_3
  openssl            conda-forge/linux-64::openssl-1.1.1g-h516909a_1
  packaging          conda-forge/noarch::packaging-20.4-pyh9f0ad1d_0
  pandas             conda-forge/linux-64::pandas-1.0.5-py38hcb8c335_0
  pandoc             conda-forge/linux-64::pandoc-2.10.1-h516909a_0
  pandocfilters      conda-forge/noarch::pandocfilters-1.4.2-py_1
  panel              conda-forge/noarch::panel-0.9.7-py_0
  param              conda-forge/noarch::param-1.9.3-py_0
  parquet-cpp        conda-forge/noarch::parquet-cpp-1.5.1-2
  parso              conda-forge/noarch::parso-0.7.1-pyh9f0ad1d_0
  partd              conda-forge/noarch::partd-1.1.0-py_0
  pcre               conda-forge/linux-64::pcre-8.44-he1b5a44_0
  pexpect            conda-forge/linux-64::pexpect-4.8.0-py38h32f6830_1
  pickleshare        conda-forge/linux-64::pickleshare-0.7.5-py38h32f6830_1001
  pillow             conda-forge/linux-64::pillow-7.2.0-py38h9776b28_1
  pip                conda-forge/noarch::pip-20.2.2-py_0
  pixman             conda-forge/linux-64::pixman-0.38.0-h516909a_1003
  poppler            conda-forge/linux-64::poppler-0.87.0-h4190859_1
  poppler-data       conda-forge/noarch::poppler-data-0.4.9-1
  postgresql         conda-forge/linux-64::postgresql-12.3-h8573dbc_0
  proj               conda-forge/linux-64::proj-7.0.0-h966b41f_5
  prometheus_client  conda-forge/noarch::prometheus_client-0.8.0-pyh9f0ad1d_0
  prompt-toolkit     conda-forge/noarch::prompt-toolkit-3.0.6-py_0
  psutil             conda-forge/linux-64::psutil-5.7.2-py38h1e0a361_0
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h14c3975_1001
  ptyprocess         conda-forge/noarch::ptyprocess-0.6.0-py_1001
  py-xgboost         rapidsai-nightly/linux-64::py-xgboost-1.1.0dev.rapidsai0.15-cuda10.2py38_1
  pyarrow            conda-forge/linux-64::pyarrow-0.17.1-py38h1234567_11_cuda
  pycparser          conda-forge/noarch::pycparser-2.20-pyh9f0ad1d_2
  pyct               conda-forge/noarch::pyct-0.4.6-py_0
  pyct-core          conda-forge/noarch::pyct-core-0.4.6-py_0
  pydeck             conda-forge/noarch::pydeck-0.4.1-pyh9f0ad1d_0
  pyee               conda-forge/noarch::pyee-7.0.2-pyh9f0ad1d_0
  pygments           conda-forge/noarch::pygments-2.6.1-py_0
  pynvml             conda-forge/noarch::pynvml-8.0.4-py_1
  pyopenssl          conda-forge/noarch::pyopenssl-19.1.0-py_1
  pyparsing          conda-forge/noarch::pyparsing-2.4.7-pyh9f0ad1d_0
  pyppeteer          conda-forge/noarch::pyppeteer-0.0.25-py_1
  pyproj             conda-forge/linux-64::pyproj-2.6.1.post1-py38h7521cb9_0
  pyrsistent         conda-forge/linux-64::pyrsistent-0.16.0-py38h1e0a361_0
  pysocks            conda-forge/linux-64::pysocks-1.7.1-py38h32f6830_1
  python             conda-forge/linux-64::python-3.8.5-h4d41432_2_cpython
  python-confluent-~ conda-forge/linux-64::python-confluent-kafka-1.3.0-py38h1e0a361_1
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  python_abi         conda-forge/linux-64::python_abi-3.8-1_cp38
  pytz               conda-forge/noarch::pytz-2020.1-pyh9f0ad1d_0
  pyviz_comms        conda-forge/noarch::pyviz_comms-0.7.6-pyh9f0ad1d_0
  pywavelets         conda-forge/linux-64::pywavelets-1.1.1-py38h8790de6_1
  pyyaml             conda-forge/linux-64::pyyaml-5.3.1-py38h1e0a361_0
  pyzmq              conda-forge/linux-64::pyzmq-19.0.2-py38ha71036d_0
  rapids             rapidsai-nightly/linux-64::rapids-0.16.0a200814-cuda10.2_py38_gc5b61d4_204
  rapids-xgboost     rapidsai-nightly/linux-64::rapids-xgboost-0.16.0a200814-cuda10.2_py38_gc5b61d4_204
  re2                conda-forge/linux-64::re2-2020.07.06-he1b5a44_1
  readline           conda-forge/linux-64::readline-8.0-he28a2e2_2
  requests           conda-forge/noarch::requests-2.24.0-pyh9f0ad1d_0
  rmm                rapidsai-nightly/linux-64::rmm-0.16.0a200814-py38_gd8ad1eb_194
  rtree              conda-forge/linux-64::rtree-0.9.4-py38h08f867b_1
  scikit-image       conda-forge/linux-64::scikit-image-0.17.2-py38hcb8c335_1
  scikit-learn       conda-forge/linux-64::scikit-learn-0.23.2-py38hee58b96_0
  scipy              conda-forge/linux-64::scipy-1.5.2-py38h8c5af15_0
  send2trash         conda-forge/noarch::send2trash-1.5.0-py_0
  setuptools         conda-forge/linux-64::setuptools-49.6.0-py38h32f6830_0
  shapely            conda-forge/linux-64::shapely-1.7.0-py38hd168ffb_3
  simpervisor        conda-forge/noarch::simpervisor-0.3-py_1
  six                conda-forge/noarch::six-1.15.0-pyh9f0ad1d_0
  snappy             conda-forge/linux-64::snappy-1.1.8-he1b5a44_3
  sortedcontainers   conda-forge/noarch::sortedcontainers-2.2.2-pyh9f0ad1d_0
  spdlog             conda-forge/linux-64::spdlog-1.7.0-hc9558a2_2
  sqlite             conda-forge/linux-64::sqlite-3.32.3-h4cf870e_1
  streamz            conda-forge/noarch::streamz-0.5.5-pyh9f0ad1d_0
  tbb                conda-forge/linux-64::tbb-2020.1-hc9558a2_0
  tblib              conda-forge/noarch::tblib-1.6.0-py_0
  terminado          conda-forge/linux-64::terminado-0.8.3-py38h32f6830_1
  testpath           conda-forge/noarch::testpath-0.4.4-py_0
  threadpoolctl      conda-forge/noarch::threadpoolctl-2.1.0-pyh5ca1d4c_0
  thrift-cpp         conda-forge/linux-64::thrift-cpp-0.13.0-h62aa4f2_2
  tifffile           conda-forge/noarch::tifffile-2020.8.13-py_0
  tiledb             conda-forge/linux-64::tiledb-1.7.7-h8efa9f0_3
  tk                 conda-forge/linux-64::tk-8.6.10-hed695b0_0
  toolz              conda-forge/noarch::toolz-0.10.0-py_0
  tornado            conda-forge/linux-64::tornado-6.0.4-py38h1e0a361_1
  tqdm               conda-forge/noarch::tqdm-4.48.2-pyh9f0ad1d_0
  traitlets          conda-forge/linux-64::traitlets-4.3.3-py38h32f6830_1
  treelite           conda-forge/linux-64::treelite-0.92-py38h4e709cc_2
  typing_extensions  conda-forge/noarch::typing_extensions-3.7.4.2-py_0
  tzcode             conda-forge/linux-64::tzcode-2020a-h516909a_0
  ucx                rapidsai-nightly/linux-64::ucx-1.8.1+g6b29558-ha5db111_0
  ucx-py             rapidsai-nightly/linux-64::ucx-py-0.16.0a200814+g6b29558-py38_57
  urllib3            conda-forge/noarch::urllib3-1.25.10-py_0
  wcwidth            conda-forge/noarch::wcwidth-0.2.5-pyh9f0ad1d_1
  webencodings       conda-forge/noarch::webencodings-0.5.1-py_1
  websockets         conda-forge/linux-64::websockets-8.1-py38h1e0a361_1
  wheel              conda-forge/noarch::wheel-0.35.0-pyh9f0ad1d_0
  widgetsnbextension conda-forge/linux-64::widgetsnbextension-3.5.1-py38h32f6830_1
  xarray             conda-forge/noarch::xarray-0.16.0-py_0
  xerces-c           conda-forge/linux-64::xerces-c-3.2.2-h8412b87_1004
  xgboost            rapidsai-nightly/linux-64::xgboost-1.1.0dev.rapidsai0.15-cuda10.2py38_1
  xorg-kbproto       conda-forge/linux-64::xorg-kbproto-1.0.7-h14c3975_1002
  xorg-libice        conda-forge/linux-64::xorg-libice-1.0.10-h516909a_0
  xorg-libsm         conda-forge/linux-64::xorg-libsm-1.2.3-h84519dc_1000
  xorg-libx11        conda-forge/linux-64::xorg-libx11-1.6.11-h516909a_0
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.9-h14c3975_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.3-h516909a_0
  xorg-libxext       conda-forge/linux-64::xorg-libxext-1.3.4-h516909a_0
  xorg-libxrender    conda-forge/linux-64::xorg-libxrender-0.9.10-h516909a_1002
  xorg-renderproto   conda-forge/linux-64::xorg-renderproto-0.11.1-h14c3975_1002
  xorg-xextproto     conda-forge/linux-64::xorg-xextproto-7.3.0-h14c3975_1002
  xorg-xproto        conda-forge/linux-64::xorg-xproto-7.0.31-h14c3975_1007
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_1
  yaml               conda-forge/linux-64::yaml-0.2.5-h516909a_0
  yarl               conda-forge/linux-64::yarl-1.4.2-py38h516909a_0
  zeromq             conda-forge/linux-64::zeromq-4.3.2-he1b5a44_3
  zfp                conda-forge/linux-64::zfp-0.5.5-he1b5a44_1
  zict               conda-forge/noarch::zict-2.0.0-py_0
  zipp               conda-forge/noarch::zipp-3.1.0-py_0
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1007
  zstd               conda-forge/linux-64::zstd-1.4.5-h6597ccf_2


Proceed ([y]/n)?
```

</details>

Going to try restarting CI in case we just ran into a sporadic issue.

rerun tests

**Comment by kkraus14** [comment]
rerun tests

**Comment by jakirkham** [comment]
It looks like `0.16` builds failed in PR ( https://github.com/rapidsai/integration/pull/107 ) as well. Is it possible these failures are unrelated?

**Comment by mike-wendt** [comment]
0.16 for CUDA 11 should fail as we don't have pkgs out for them yet. That said the rest of 0.16 should solve and it is not

**Comment by mike-wendt** [comment]
For instance this should solve and it does not - https://gpuci.gpuopenanalytics.com/job/rapidsai/job/integration/job/prb/job/meta-pkg-nightly-build/195/CONDA_CONFIG_FILE=conda%2Frecipes%2Fversions.yaml,CONDA_USERNAME=rapidsai-nightly,CUDA_VER=10.2,DEFAULT_CUDA_VER=10.1,PYTHON_VER=3.7,RAPIDS_VER=0.16.0a/console

I need to know why it doesn't solve before we can approve this merge. Is there a misconfig in a 0.16 pkg somewhere? Is there a missing pkg?

**Comment by mike-wendt** [comment]
> It looks like `0.16` builds failed in PR ( #107 ) as well. Is it possible these failures are unrelated?

@raydouglass should be able to help see if this PR is the cause or not

**Comment by jakirkham** [comment]
FWIW all of the 0.16 builds (not just CUDA 11) failed in that PR as well. Anyways not trying to pick on that PR. More just trying to say that the failures don't appears specific to this change. Also am trying to figure out if these 0.16 failures are otherwise known or expected at this point.

**Comment by mike-wendt** [comment]
> FWIW all of the 0.16 builds (not just CUDA 11) failed in that PR as well. Anyways not trying to pick on that PR. More just trying to say that the failures don't appears specific to this change. Also am trying to figure out if these 0.16 failures are otherwise known or expected at this point.

I understand John, but as that PR is merged, I'm trying to ask for triage for the given output here. @raydouglass said he would also look into this and help. I'm fine with #107 introduced X and is missing Y so it causes this PR to also fail. Then we can patch it. Without the info no matter the origin we can't proceed is all I'm saying.

**Comment by raydouglass** [comment]
I think I've found the problem. Waiting on a new build of xgboost and then a new PR to test and fix.

**Comment by raydouglass** [comment]
Fix is in https://github.com/rapidsai/integration/pull/111

**Comment by mike-wendt** [comment]
#111 is merged

rerun tests

**Comment by jakirkham** [comment]
Thanks all! 😀

**Pull request merged**
