### PR TITLE
FIX Add rapids-pytest-benchmark pkg for cugraph tests

### PR DESCRIPTION
**Pull request by mike-wendt**
Follows #190

Applies patch to branch-0.18

### CODE REVIEW

**Comment by mike-wendt** [comment]
`gpuCI/build/rapids-integration-tests` failed due to missing RAPIDS images; will wait for them to be built tomorrow and then tests and merge

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mike-wendt** [comment]
Blocked until `runtime` images are fixed

**Review by dillon-cullinan — APPROVED** [review]

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Pull request merged**
