### PR TITLE
Add mimesis for generating data in Python tests

### PR DESCRIPTION
**Pull request by calebwin**
https://github.com/rapidsai/cudf/pull/5843/ introduces a `dataset_synthesizer` module used by Python tests for automatically synthesizing datasets. `dataset_synthesizer` uses `mimesis` for randomly generating data.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by raydouglass** [comment]
ok to test

**Comment by calebwin** [comment]
@raydouglass Do I need to change something for these checks to succeed?

**Comment by raydouglass** [comment]
> Do I need to change something for these checks to succeed?

Looks like the v0.15 passed, so we'll ignore the other failures for now.

**Pull request merged**
